Add update, put and delete
SergeiDemyanenko/ToDo pull request #11
Opened 2021-04-27 04:12 UTC by Wis13

My solution of the task

2021-04-27 05:52 UTC, SergeiKuznetsov commented
Не понятно что добавляет этот PR.  Описания изменений нет.
Почему удалены большие куски кода?
Сам добавленный код не работает. 😟

2021-04-27 05:57 UTC, SergeiKuznetsov requested changes

2021-04-27 05:57 UTC, SergeiKuznetsov commented on pom.xml
> +
Почему удалено?

2021-04-27 05:57 UTC, SergeiKuznetsov commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Это был рабочий код. Не надо затирать чужую работу наверное.

2021-04-27 16:48 UTC, Wis13 commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Я не затирал ничего, а только решил конфликт в своей ветке. Сорри если сделал что то не так, я просто только учусь работать в команде.

2021-04-27 16:54 UTC, Wis13 commented on pom.xml
> +
За ненадобностью, и без него все работает! Чем меньше зависимостей тем легче дебажить код.

2021-04-27 17:07 UTC, Wis13 commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Просто реализация немного другая, есть отличия и в функциональности. Например у меня update не переписывает весь объект, а только меняет значения тех ключей что находятся в боди. Это может быть полезно когда объект имеет большое колличество полей, и в этом случае не нужно в JSON при update одного перечислять их все. Кстати только что еще раз проверил код все отлично работает!

2021-04-27 21:41 UTC, Wis13 commented on src/main/java/org/example/controller/TodoController.java
> -        int newId = todoRepo.addTodoItem(task, isDone, date );
Мне кажется не совсем корректно использовать "@GetMapping и для GET и для POST изменяя только endpoint, vj;tn z rjytxyj yt ghfd

2021-04-27 21:43 UTC, Wis13 commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Этот код (который рабочий и написан выше) написан как простое java-application, а не не спринг бут :) У меня в параметрах метода не праметры конструктора, а бин созданный spring boot

2021-04-27 21:48 UTC, SergeiKuznetsov commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Мне кажется тема разрешения конфликтов самая сложная в коллективной работе. На лекциях прошлого потока её прошли вскользь и не разобрали толком.

2021-04-27 21:50 UTC, SergeiKuznetsov commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Легко работать когда один. Можно даже описания коммитов не прописывать подробно.
Но если мы в команде, то каждый коммит и запрос на слияние должен мне кажется включать подробные комментарии к тому, что предлагается изменить в проекте и почему. 
Иначе просто видим что много кода перелопачено кардинально, но сложно понять почему.

2021-04-27 23:09 UTC, Wis13 commented on src/main/java/org/example/repository/TodoRepository.java
> -        return newId;
Согласен

2021-05-03 04:08 UTC, ke-de-ve approved these changes

2021-05-03 04:09 UTC, SergeiKuznetsov approved these changes

2021-05-03 04:11 UTC, merged