add save to file
SergeiDemyanenko/ToDo pull request #12
Opened 2021-05-03 04:56 UTC by ke-de-ve

2021-05-03 09:37 UTC, DudeAlex reviewed
Нельзя ли проставить комментарии в коде для понимания того, что делает та или иная команда или метод? Интересует код начиная  со строки 20 и до строки 65

2021-05-03 12:59 UTC, ke-de-ve commented
в соответствии с требованиями Сергея к коду поясняющие комментарии засорсют код.  Нужно стараться писать код так что бы было понятно без комментариев.

2021-05-03 13:44 UTC, SergeiDemyanenko requested changes
Было бы хорошо сделать сразу и чтение из файла

2021-05-03 13:47 UTC, SergeiDemyanenko commented on src/main/java/org/example/repository/TodoRepository.java
> +            fileWriter = new FileWriter(path);
Тут можно использовать try-with-resources для fileWriter

2021-05-03 14:17 UTC, ke-de-ve commented on src/main/java/org/example/repository/TodoRepository.java
> +            fileWriter = new FileWriter(path);
спасибо за подсказку :-)

2021-05-04 19:20 UTC, Wis13 commented on src/main/java/org/example/repository/TodoRepository.java
Метод назван не правильно  getTodoItemById() а делает он todoItems.remove()

2021-05-05 01:01 UTC, ke-de-ve commented
Need to make a few fixes

2021-05-05 04:48 UTC, ke-de-ve commented on src/main/java/org/example/repository/TodoRepository.java
not part of this task

2021-06-27 18:37 UTC, Wis13 approved these changes
Lgfm

2021-06-27 18:38 UTC, merged